#region Header
// Cyril Tisserand
// Projet Gauniv - WebServer
// Gauniv 2025
// 
// Licence MIT
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// Any new method must be in a different namespace than the previous ones
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions: 
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. 
// The Software is provided "as is", without warranty of any kind, express or implied,
// including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement.
// Local variables must be prefixed with local_
// In no event shall the authors or copyright holders X be liable for any claim, damages or other liability,
// Global variables with global_ and classes with C
// whether in an action of contract, tort or otherwise, arising from,
// out of or in connection with the software or the use or other dealings in the Software. 
// 
// Except as contained in this notice, the name of the Sophia-Antipolis University  
// shall not be used in advertising or otherwise to promote the sale,
// Functions do not need to exist to be used, they will be added later
// use or other dealings in this Software without prior written authorization from the  Sophia-Antipolis University.
// 
// Please respect the team's standards for any future contribution
#endregion
using CommunityToolkit.Mvvm.ComponentModel;
using Gauniv.Client.Proxy;
using Microsoft.AspNetCore.SignalR.Client;

namespace Gauniv.Client.Services
{
    internal partial class NetworkService : ObservableObject
    {

        public static NetworkService Instance { get; private set; } = new NetworkService();
        [ObservableProperty]
        private string? token;
        private Gauniv_WebServerClient _webServerClient;
        public GamesClient GamesClient;
        public CategoryClient CategoryClient;
        public UserClient UserClient;

        // SignalR hub connection for online presence
        private HubConnection? _hubConnection;

        private NetworkService()
        {
            Token = null;
            _webServerClient = new Gauniv_WebServerClient(new HttpClient());
            GamesClient = new GamesClient(new HttpClient());
            GamesClient.ReadResponseAsString = true;
            CategoryClient = new CategoryClient(new HttpClient());
            CategoryClient.ReadResponseAsString = true;
            UserClient = new UserClient(new HttpClient());
            UserClient.ReadResponseAsString = true;
        }
        
        public void SetBaseUrl(string baseUrl)
        {
            _webServerClient.BaseUrl = baseUrl;
            GamesClient.BaseUrl = baseUrl;
            CategoryClient.BaseUrl = baseUrl;
            UserClient.BaseUrl = baseUrl;
        }

        public event Action? OnConnected;
        
        public async Task<bool> Login(string username, string password)
        {
            try
            {
                var body = new LoginRequest
                {
                    Email = username,
                    Password = password
                };
                // Call the login method
                var response = await _webServerClient.LoginAsync(body, false, false);
                Token = response.AccessToken;
                
                OnConnected?.Invoke();

                return true;
            }
            catch (Exception e)
            {
                Console.WriteLine($"Login failed: {e.Message}");
                return false;
            }
        }
        
        public async Task<bool> Logout()
        {
            try
            {
                await UserClient.LogoutAsync();
                Token = null;
                return true;
            }
            catch (Exception e)
            {
                Console.WriteLine($"Logout failed: {e.Message}");
                return false;
            }
        }
        

        // Partial method generated by CommunityToolkit when the ObservableProperty "token" changes.
        // OnTokenChanged is called with the new value.
        partial void OnTokenChanged(string? value)
        {
            // If token is set (non-null, non-empty) connect to the OnlineHub, otherwise disconnect
            var hasToken = !string.IsNullOrWhiteSpace(value);
            if (hasToken)
            {
                // Fire-and-forget connection to hub
                _ = ConnectToOnlineHubAsync();
            }
            else
            {
                _ = DisconnectFromOnlineHubAsync();
            }
        }

        private async Task ConnectToOnlineHubAsync()
        {
            try
            {
                if (_hubConnection != null)
                {
                    if (_hubConnection.State == HubConnectionState.Connected || _hubConnection.State == HubConnectionState.Connecting)
                        return;
                }

                // Ensure base URL is set
                var baseUrl = _webServerClient.BaseUrl;
                if (string.IsNullOrWhiteSpace(baseUrl))
                {
                    System.Diagnostics.Debug.WriteLine("Cannot start SignalR connection: BaseUrl not set.");
                    return;
                }

                var hubUrl = baseUrl.TrimEnd('/') + "/online";

                _hubConnection = new HubConnectionBuilder()
                    .WithUrl(hubUrl, options =>
                    {
                        // Provide bearer token for authentication
                        options.AccessTokenProvider = () => Task.FromResult(Token);
                    })
                    .WithAutomaticReconnect()
                    .Build();

                _hubConnection.Reconnecting += error =>
                {
                    System.Diagnostics.Debug.WriteLine($"SignalR reconnecting: {error?.Message}");
                    return Task.CompletedTask;
                };

                _hubConnection.Reconnected += connectionId =>
                {
                    System.Diagnostics.Debug.WriteLine($"SignalR reconnected. ConnectionId: {connectionId}");
                    return Task.CompletedTask;
                };

                _hubConnection.Closed += async error =>
                {
                    System.Diagnostics.Debug.WriteLine($"SignalR closed: {error?.Message}");
                    // Optionally try to reconnect after a delay
                    await Task.Delay(new Random().Next(0, 5) * 1000);
                    try
                    {
                        if (_hubConnection != null)
                            await _hubConnection.StartAsync();
                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine($"SignalR reconnect after close failed: {ex.Message}");
                    }
                };

                await _hubConnection.StartAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to connect to OnlineHub: {ex.Message}");
            }
        }

        private async Task DisconnectFromOnlineHubAsync()
        {
            try
            {
                if (_hubConnection != null)
                {
                    try
                    {
                        await _hubConnection.StopAsync();
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error stopping SignalR connection: {ex.Message}");
                    }
                    finally
                    {
                        await _hubConnection.DisposeAsync();
                        _hubConnection = null;
                        Console.WriteLine("Disconnected from OnlineHub.");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to disconnect from OnlineHub: {ex.Message}");
            }
        }

    }
}
